# Generated by Django 4.2.6 on 2023-10-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('score_time', models.CharField(max_length=100)),
                ('score_service', models.CharField(max_length=100)),
                ('score_attention', models.CharField(max_length=100)),
                ('score_recomment', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('date', models.DateField()),
                ('id_turn', models.IntegerField()),
            ],
        ),
    ]
